# Generated by Django 4.1.1 on 2022-11-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiclabsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
