# Generated by Django 4.1.1 on 2022-12-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiclabsite', '0003_alter_album_image_alter_author_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
