# Generated by Django 4.1.1 on 2023-01-27 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musiclabsite', '0006_song_single'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='single',
        ),
        migrations.DeleteModel(
            name='Single',
        ),
    ]
